import Product from "../models/Product";

const demoProducts = [
  {
    name: "Noor Embroidered Lehenga",
    slug: "noor-embroidered-lehenga",
    description: "Stunning heavy embroidered lehenga with intricate zari work, perfect for weddings and festive occasions.",
    category: "Lehenga",
    images: ["https://picsum.photos/seed/leh1/800/1000", "https://picsum.photos/seed/leh2/800/1000"],
    price: 4499,
    originalPrice: 6999,
    discountPercent: 35,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "Royal Blue", hex: "#1E3A8A" },
      { name: "Maroon", hex: "#7F1D1D" },
      { name: "Mint Green", hex: "#6EE7B7" },
    ],
    stock: 20,
    rating: 4.8,
    reviewCount: 124,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    name: "Ananya Floral Frock",
    slug: "ananya-floral-frock",
    description: "Delicate floral print frock with puff sleeves and a tiered skirt.",
    category: "Frock",
    images: ["https://picsum.photos/seed/frock1/800/1000"],
    price: 1299,
    originalPrice: 1999,
    discountPercent: 35,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "Pastel Blue", hex: "#BAE6FD" },
      { name: "Peach", hex: "#FBBF9D" },
      { name: "White", hex: "#FFFFFF" },
    ],
    stock: 50,
    rating: 4.5,
    reviewCount: 89,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    name: "Zara Cotton Kurti Set",
    slug: "zara-cotton-kurti-set",
    description: "Comfortable and stylish cotton kurti with block print detailing.",
    category: "Kurti",
    images: ["https://picsum.photos/seed/kurti1/800/1000"],
    price: 899,
    originalPrice: 1499,
    discountPercent: 40,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "Indigo", hex: "#3730A3" },
      { name: "Teal", hex: "#0F766E" },
      { name: "Pink", hex: "#EC4899" },
    ],
    stock: 100,
    rating: 4.7,
    reviewCount: 203,
    isFeatured: true,
    isNewArrival: true,
  },
  {
    name: "Royal Silk Suit",
    slug: "royal-silk-suit",
    description: "Luxurious silk suit with intricate embroidery on the yoke and sleeves.",
    category: "Suit",
    images: ["https://picsum.photos/seed/suit1/800/1000"],
    price: 2799,
    originalPrice: 3999,
    discountPercent: 30,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "Navy Blue", hex: "#1E3A8A" },
      { name: "Forest Green", hex: "#166534" },
      { name: "Wine", hex: "#881337" },
    ],
    stock: 30,
    rating: 4.6,
    reviewCount: 67,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    name: "Banarasi Silk Saree",
    slug: "banarasi-silk-saree",
    description: "Authentic Banarasi silk saree with zari brocade work.",
    category: "Saree",
    images: ["https://picsum.photos/seed/saree1/800/1000"],
    price: 3499,
    originalPrice: 5499,
    discountPercent: 36,
    sizes: ["Free Size"],
    colors: [
      { name: "Deep Red", hex: "#991B1B" },
      { name: "Royal Blue", hex: "#1E3A8A" },
      { name: "Golden", hex: "#D4AF37" },
    ],
    stock: 15,
    rating: 4.9,
    reviewCount: 156,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    name: "Pearl Co-ord Set",
    slug: "pearl-coord-set",
    description: "Trendy co-ord set featuring a cropped top and wide-leg pants.",
    category: "Co-ord Set",
    images: ["https://picsum.photos/seed/coord1/800/1000"],
    price: 1999,
    originalPrice: 2999,
    discountPercent: 33,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "Ivory", hex: "#FFFFF0" },
      { name: "Blush Pink", hex: "#FBCFE8" },
      { name: "Sage", hex: "#84CC16" },
    ],
    stock: 25,
    rating: 4.4,
    reviewCount: 45,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    name: "Chanderi Anarkali Suit",
    slug: "chanderi-anarkali-suit",
    description: "Graceful Chanderi Anarkali with floral hand block prints.",
    category: "Suit",
    images: ["https://picsum.photos/seed/suit2/800/1000"],
    price: 2199,
    originalPrice: 3499,
    discountPercent: 37,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "Powder Blue", hex: "#BAE6FD" },
      { name: "Mustard", hex: "#D97706" },
      { name: "Rose", hex: "#E11D48" },
    ],
    stock: 40,
    rating: 4.5,
    reviewCount: 78,
    isFeatured: false,
    isNewArrival: false,
  },
  {
    name: "Marigold Printed Lehenga",
    slug: "marigold-printed-lehenga",
    description: "Vibrant marigold printed lehenga with mirror-work details.",
    category: "Lehenga",
    images: ["https://picsum.photos/seed/leh3/800/1000"],
    price: 3299,
    originalPrice: 4999,
    discountPercent: 34,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "Yellow", hex: "#FDE047" },
      { name: "Orange", hex: "#F97316" },
      { name: "Pink", hex: "#EC4899" },
    ],
    stock: 18,
    rating: 4.6,
    reviewCount: 92,
    isFeatured: true,
    isNewArrival: true,
  },
  {
    name: "Pastel Georgette Saree",
    slug: "pastel-georgette-saree",
    description: "Elegant pastel georgette saree with sequin border work.",
    category: "Saree",
    images: ["https://picsum.photos/seed/saree2/800/1000"],
    price: 2499,
    originalPrice: 3999,
    discountPercent: 37,
    sizes: ["Free Size"],
    colors: [
      { name: "Lavender", hex: "#C4B5FD" },
      { name: "Mint", hex: "#6EE7B7" },
      { name: "Peach", hex: "#FBBF9D" },
    ],
    stock: 22,
    rating: 4.7,
    reviewCount: 111,
    isFeatured: false,
    isNewArrival: false,
  },
  {
    name: "Chikankari Kurti",
    slug: "chikankari-kurti",
    description: "Authentic Lucknowi chikankari hand-embroidered kurti in breathable cotton.",
    category: "Kurti",
    images: ["https://picsum.photos/seed/kurti2/800/1000"],
    price: 1199,
    originalPrice: 1799,
    discountPercent: 33,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Sky Blue", hex: "#BAE6FD" },
      { name: "Lemon", hex: "#FEF08A" },
    ],
    stock: 60,
    rating: 4.8,
    reviewCount: 187,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    name: "Midnight Velvet Lehenga",
    slug: "midnight-velvet-lehenga",
    description: "Opulent velvet bridal lehenga embellished with gold zardozi and kundan work.",
    category: "Lehenga",
    images: ["https://picsum.photos/seed/leh4/800/1000"],
    price: 5999,
    originalPrice: 8999,
    discountPercent: 33,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "Midnight Blue", hex: "#1E3A8A" },
      { name: "Deep Maroon", hex: "#7F1D1D" },
      { name: "Emerald", hex: "#065F46" },
    ],
    stock: 10,
    rating: 4.9,
    reviewCount: 43,
    isFeatured: true,
    isNewArrival: true,
  },
  {
    name: "Mango Yellow Co-ord Set",
    slug: "mango-yellow-coord-set",
    description: "Bright and cheerful mango yellow co-ord set with tropical print.",
    category: "Co-ord Set",
    images: ["https://picsum.photos/seed/coord2/800/1000"],
    price: 1799,
    originalPrice: 2499,
    discountPercent: 28,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "Yellow", hex: "#FDE047" },
      { name: "Coral", hex: "#F97316" },
      { name: "White", hex: "#FFFFFF" },
    ],
    stock: 35,
    rating: 4.3,
    reviewCount: 56,
    isFeatured: false,
    isNewArrival: false,
  },
  {
    name: "Ivory Linen Suit Set",
    slug: "ivory-linen-suit-set",
    description: "Sophisticated linen suit set with minimal embroidery.",
    category: "Suit",
    images: ["https://picsum.photos/seed/suit3/800/1000"],
    price: 1699,
    originalPrice: 2299,
    discountPercent: 26,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "Ivory", hex: "#FFFFF0" },
      { name: "Sand", hex: "#D4A574" },
      { name: "Slate", hex: "#64748B" },
    ],
    stock: 45,
    rating: 4.5,
    reviewCount: 61,
    isFeatured: false,
    isNewArrival: false,
  },
  {
    name: "Rustic Rose Frock",
    slug: "rustic-rose-frock",
    description: "Romantic midi frock with rose-print fabric and sweetheart neckline.",
    category: "Frock",
    images: ["https://picsum.photos/seed/frock2/800/1000"],
    price: 1499,
    originalPrice: 2199,
    discountPercent: 32,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "Rose", hex: "#F43F5E" },
      { name: "Dusty Pink", hex: "#FBCFE8" },
      { name: "Berry", hex: "#9D174D" },
    ],
    stock: 38,
    rating: 4.4,
    reviewCount: 73,
    isFeatured: false,
    isNewArrival: true,
  },
  {
    name: "Teal Kanjivaram Saree",
    slug: "teal-kanjivaram-saree",
    description: "Exquisite Kanjivaram silk saree with temple-border design and rich golden zari.",
    category: "Saree",
    images: ["https://picsum.photos/seed/saree3/800/1000"],
    price: 4999,
    originalPrice: 7499,
    discountPercent: 33,
    sizes: ["Free Size"],
    colors: [
      { name: "Teal", hex: "#0F766E" },
      { name: "Purple", hex: "#7C3AED" },
      { name: "Navy", hex: "#1E3A8A" },
    ],
    stock: 12,
    rating: 4.8,
    reviewCount: 98,
    isFeatured: true,
    isNewArrival: false,
  },
  {
    name: "Lavender Embroidered Kurti",
    slug: "lavender-embroidered-kurti",
    description: "Elegant lavender kurti with thread embroidery on the yoke and sleeve hem.",
    category: "Kurti",
    images: ["https://picsum.photos/seed/kurti3/800/1000"],
    price: 1099,
    originalPrice: 1599,
    discountPercent: 31,
    sizes: ["S", "M", "L", "XL", "XXL", "3XL", "4XL", "5XL", "6XL"],
    colors: [
      { name: "Lavender", hex: "#C4B5FD" },
      { name: "Lilac", hex: "#A78BFA" },
      { name: "White", hex: "#FFFFFF" },
    ],
    stock: 55,
    rating: 4.6,
    reviewCount: 134,
    isFeatured: true,
    isNewArrival: false,
  },
];

export async function seedProducts() {
  try {
    console.log("Checking if products need to be seeded...");
    const count = await Product.countDocuments();
    console.log(`Current product count: ${count}`);
    if (count === 0) {
      console.log("Seeding demo products...");
      console.log("First product to seed:", JSON.stringify(demoProducts[0], null, 2));
      await Product.insertMany(demoProducts);
      console.log("Demo products seeded successfully");
    } else {
      console.log("Products already exist, skipping seed.");
    }
  } catch (err) {
    console.error("Error seeding products:", err);
  }
}
